# =================================================================
# ALA Application - Azure HTTPS Production Deployment
# =================================================================
# This extends the base azure configuration with HTTPS support
# Usage: docker-compose -f docker-compose.azure.yml -f docker-compose.https.yml up -d
#
# Features:
# - Automatic Let's Encrypt SSL certificates
# - Nginx reverse proxy with HTTPS redirect
# - No sudo required - pure Docker solution

services:
  # =================================================================
  # Nginx Reverse Proxy with Let's Encrypt
  # =================================================================
  nginx-proxy:
    image: nginxproxy/nginx-proxy:latest
    container_name: ala-nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - ./nginx-proxy.conf:/etc/nginx/conf.d/proxy.conf:ro
    restart: unless-stopped
    networks:
      - ala-network

  letsencrypt:
    image: nginxproxy/acme-companion:latest
    container_name: ala-letsencrypt
    environment:
      - DEFAULT_EMAIL=admin@alphatau.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - acme-state:/etc/acme.sh
    restart: unless-stopped
    depends_on:
      - nginx-proxy
    networks:
      - ala-network

  # =================================================================
  # Backend API - Updated for HTTPS
  # =================================================================
  api:
    environment:
      - VIRTUAL_HOST=alaapp.israelcentral.cloudapp.azure.com
      - VIRTUAL_PATH=/api
      - VIRTUAL_PORT=5000
      - LETSENCRYPT_HOST=alaapp.israelcentral.cloudapp.azure.com
      - LETSENCRYPT_EMAIL=admin@alphatau.com
    # Remove direct port mapping - proxy handles it
    ports: []
    
  # =================================================================
  # Frontend Application - Updated for HTTPS
  # =================================================================
  frontend:
    environment:
      - VIRTUAL_HOST=alaapp.israelcentral.cloudapp.azure.com
      - VIRTUAL_PATH=/
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=alaapp.israelcentral.cloudapp.azure.com
      - LETSENCRYPT_EMAIL=admin@alphatau.com
    # Remove direct port mapping - proxy handles it
    ports: []

# =================================================================
# Additional Volumes for HTTPS
# =================================================================
volumes:
  nginx-certs:
    driver: local
  nginx-vhost:
    driver: local
  nginx-html:
    driver: local
  acme-state:
    driver: local