FROM node:20.13-alpine

WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install ALL dependencies including development dependencies
RUN npm install

# Copy the rest of the code
COPY . .

# Expose the development port
EXPOSE 3000

# Set environment variables
ENV NODE_ENV=development

# Command to run the development server
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
