# Base configuration shared across environments
# This file contains minimal shared configuration between development and production

services:
  # Backend API
  api:
    build:
      context: ./backend
    depends_on:
      - db
    networks:
      - ala-network
    restart: unless-stopped

  # Frontend application
  frontend:
    build:
      context: ./frontend
    depends_on:
      - api
    networks:
      - ala-network
    restart: unless-stopped

  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    networks:
      - ala-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  ala-network:
    driver: bridge

volumes:
  postgres-data:
  api-logs:
