version: '3.8'

services:
  # Backend API
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ala-api-prod
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DATABASE_URL=postgres://postgres:postgres@db:5432/ala_db
      - ENABLE_SSL=false
      - JWT_SECRET=your-jwt-secret-key-change-in-production
      - PRIORITY_URL=https://t.eu.priority-connect.online/odata/Priority/tabbtbc6.ini/test24/
    ports:
      - "5000:5000"
    networks:
      - ala-network
    volumes:
      - api-logs:/usr/src/app/logs

  # Frontend application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ala-frontend-prod
    restart: unless-stopped
    environment:
      - API_URL=http://api:5000
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - ala-network

  # PostgreSQL Database
  db:
    image: postgres:16.6-alpine
    container_name: ala-db-prod
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ala_db
    ports:
      - "5432:5432"
    networks:
      - ala-network
    volumes:
      - postgres-data-prod:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  ala-network:
    driver: bridge

volumes:
  postgres-data-prod:
  api-logs:
