services:
  # Backend API for development
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: ala-api-dev
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DATABASE_URL=postgres://postgres:postgres@db:5432/ala_db
      - ENABLE_SSL=false
      - JWT_SECRET=dev-jwt-secret-key
      - PRIORITY_URL=https://t.eu.priority-connect.online/odata/Priority/tabbtbc6.ini/test24/
      - PRIORITY_MOCK=true  # Enable mock responses for development
    ports:
      - "5000:5000"
    networks:
      - ala-network
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  # Frontend application for development
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: ala-frontend-dev
    restart: unless-stopped
    environment:
      # Use direct backend service name inside docker network
      - VITE_API_URL=http://api:5000/api
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - ala-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules

  # PostgreSQL Database
  db:
    image: postgres:16.6-alpine
    container_name: ala-db-dev
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ala_db
    ports:
      - "5432:5432"
    networks:
      - ala-network
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  ala-network:
    driver: bridge

volumes:
  postgres-data-dev:
