version: '3.8'

services:
  # Backend API
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: ala-api-dev
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DATABASE_URL=postgres://postgres:postgres@db:5432/ala_db
      - ENABLE_SSL=false
      - JWT_SECRET=dev-secret-key
      - PRIORITY_URL=https://t.eu.priority-connect.online/odata/Priority/tabbtbc6.ini/test24/
    ports:
      - "5000:5000"
    networks:
      - ala-network
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  # Frontend application in development mode
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: ala-frontend-dev
    restart: unless-stopped
    environment:
      - VITE_API_URL=http://localhost:5000
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - ala-network
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules

  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: ala-db-dev
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ala_db
    ports:
      - "5432:5432"
    networks:
      - ala-network
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data

networks:
  ala-network:
    driver: bridge

volumes:
  postgres-data-dev:
