# =================================================================
# ALA Application - Production Override Configuration
# =================================================================
# This file extends docker-compose.yml for production deployments
# Usage: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up
#
# Production-specific features:
# - Optimized build targets (multi-stage builds)
# - No volume mounts (immutable containers)
# - Production environment variables
# - Security-hardened configurations
# - Health checks and restart policies

services:
  # =================================================================
  # Backend API - Production Overrides
  # =================================================================
  api:
    build:
      target: production  # Use production stage
    environment:
      # Production-specific environment variables
      - NODE_ENV=production
      - LOG_LEVEL=info
      - PRIORITY_MOCK=false
    restart: always
    # No volume mounts in production (immutable containers)
    # Remove development volumes if they exist
    volumes: []

  # =================================================================
  # Frontend Application - Production Overrides
  # =================================================================
  frontend:
    build:
      target: production  # Use production stage (nginx)
    environment:
      # Production-specific environment variables
      - NODE_ENV=production
      - VITE_API_URL=/api  # Relative URL for production
      - VITE_ENVIRONMENT=production
      - VITE_OFFLINE_STORAGE=false
    ports:
      - "80:80"  # Production port (HTTP)
      # For HTTPS, add: - "443:443"
    restart: always
    # Production health check on port 80
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    # No volume mounts in production
    volumes: []

  # =================================================================
  # Database - Production Overrides
  # =================================================================
  db:
    environment:
      # Production database settings
      - POSTGRES_DB=ala_db
      # Enable connection logging for production monitoring
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256 --log-statement=all
    restart: always
    # Don't expose database port in production (security)
    ports: []
    volumes:
      # Use production-specific volume
      - postgres-data-prod:/var/lib/postgresql/data

# =================================================================
# Production-Specific Volumes
# =================================================================
volumes:
  postgres-data-prod:
    name: ala-postgres-data-prod